### ISSUE TITLE
ndarray is not C-contiguous error, when using grog and switching the coil axis

### ISSUE THREAD

**Issue by schadol** [mckib2/pygrappa#100]
Hi Nicholas,
thank you for this amazing python implementation!
I tried to use the grog and got an error, when changing the location of the coil axis.
This is because using np.moveaxis to move the coils to the back makes the ndarray not C-contiguous.
A fix would be to apply np.ascontiguousarray() after the np.moveaxis()-operation.

Best regards,
Olli

**Comment by mckib2** [comment]
Hi @schadol, apologies for getting back to you so late.  I'm taking a look now to see if I can reproduce.  Happy to apply your suggestion of I can

**Comment by mckib2** [comment]
Took a slightly different route and modified the Cython routine to handle both C and Fortran ordered arrays.  I'll get a release out with this fix this evening

**Comment by mckib2** [comment]
New wheels and source dist have been uploaded to PyPI!
