### ISSUE TITLE
Import error: version GLIBC_2.29 not found

### ISSUE THREAD

**Issue by Jerzy97** [mckib2/pygrappa#104]
Hi,

upon installing the package via `pip install pygrappa`, I encountered an import error.
I send a screenshot with the error message.

![Screenshot from 2024-09-18 13-25-45](https://github.com/user-attachments/assets/924d5479-d676-4dc9-926f-8dae8c0ecc1d)

I have installed pygrappa in a conda environment. I can give more info regarding the environment, if necessary.

Thanks a lot for maintaining this package. It is really valuable!
Best, Georg

**Comment by mckib2** [comment]
Hi @Jerzy97 , thanks for reporting.  I think what is happening here is that there are some precompiled binaries available on pypi that are being used with a `pip install pygrappa` and these binaries are getting old enough that they are not compatible with your system.   Installing via `pip install .` will build sources locally I believe, so the same/compatible glibc will definitely be used.

I'll go ahead and redeploy the binaries in a new version to make sure they aren't stale.  I'll let you know when they're available.

**Comment by mckib2** [comment]
Just uploaded version 0.26.3.  PyPI reports `CPython 3.12 manylinux: glibc 2.17+ x86-64` for the Python 3.12 x86-64 target.  Hopefully that will be compatible with your conda environment.

If you get a chance, please try installing in a fresh conda environment from PyPI and report back if it now succeeds or still fails.

**Comment by Jerzy97** [comment]
Dear @mckib2 
sorry for such a late reply! I just tried in a new environment - it seems to work perfectly currently!
Thank you very much again!
