### ISSUE TITLE
bad result in vcgrappa when R=3

### ISSUE THREAD

**Issue by kingaza** [mckib2/pygrappa#71]
I am quite confused...
the code in basic_vcgrappa.py is modified as 
```
    kspace[1::3, ...] = 0
    kspace[2::3, ...] = 0
```
![vcgrappa_x3](https://user-images.githubusercontent.com/1664610/83271290-3caca780-a1fc-11ea-8959-defcedd29c20.png)

While the results are quite good when R equals to 2 or 4
![vcgrappa_x2](https://user-images.githubusercontent.com/1664610/83271565-9f05a800-a1fc-11ea-8e93-04c45da560de.png)
![vcgrappa_x4](https://user-images.githubusercontent.com/1664610/83271589-a62cb600-a1fc-11ea-970d-15202d1ab978.png)

**Comment by mckib2** [comment]
I can recreate this issue.  Is this due to the center line of kspace being omitted?  I think in general you want to include the center of kspace.

Try:
```
# R=3
kspace[0::3, ...] = 0
kspace[2::3, ...] = 0
```

Using the above I get the following:
![image](https://user-images.githubusercontent.com/28734319/83281535-75656600-a195-11ea-9c14-3174ecaec8f1.png)

**Comment by kingaza** [comment]
yes, I got the same result as you. Thank you for the hint.
But why vcgrappa is so sensitive to the center line? I don't remember the paper mentioned about it...

**Comment by mckib2** [comment]
I can't say why it's so sensitive, that's an interesting result.  Do you know of any other reference VC-GRAPPA implementations that we could test against?

**Comment by mckib2** [comment]
Related to #72

**Comment by kingaza** [comment]
I tested it with real data, and it worked. But the improvement is not always significant as mentioned in the paper. 
This issue is closed as I have no idea how to evaluate it further. Anyway, it can be traced by the new one [#72](https://github.com/mckib2/pygrappa/issues/72)
