### ISSUE TITLE
skimage.util.pad not available

### ISSUE THREAD

**Issue by lukasfolle** [mckib2/pygrappa#91]
Recent install fails due to the latest scikit-image release: https://github.com/scikit-image/scikit-image/releases which dropped `skimage.util.pad`. 
Should be possible to fix this by replacing it with `np.pad`.

**Comment by mckib2** [comment]
Yes, thanks for raising an issue here.  It's about time we regenerated the wheels for the latest platforms as well

**Comment by mckib2** [comment]
I updated dependencies in `requirements.txt` to the latest version my pip would install -- please open a new issue if this is too restrictive for your use case and we can try to relax them
