### ISSUE TITLE
Local utils package cannot be imported properly

### ISSUE THREAD

**Issue by GuoyaoShen** [mckib2/pygrappa#97]
Hi,

I just found that after pip installing this package, all my projects' local submodules located in ./utils cannot be imported properly. After uninstalling pygrappa they worked again. So I think this might because the utils package in grappa get the highest priority. 

So I'm wondering is there any way to fix this instead of staying away from subfolder named 'utils' in all of my local projects? Thanks!

**Comment by mckib2** [comment]
Hi @GuoyaoShen, thanks for the report.  Indeed, pygrappa/utils should not be at the root level of the project.  I will hopefully have time to fix this and make a new release in the next few days

**Comment by mckib2** [comment]
I'll reopen until I've fixed the wheel generation and deployed a new release

**Comment by mckib2** [comment]
@GuoyaoShen New wheels are available on pypi -- please reopen if you're still having issues!
